version: '3.7'

services:
  historie-data-service:
    container_name: historie-data-service
    image: haalcentraal.azurecr.io/gba-historie-api:2.0.1-202405311615
    environment:
      - ASPNETCORE_URLS=http://+;
      - Database__Host=postgres
      - Database__Username=root
      - Database__Password=root
      - Database__Database=rvig_haalcentraal_testdata
      - HaalcentraalApi__MaxSearchResults=10
      - ProtocolleringAuthorization__UseAuthorizationChecks=false
      - ProtocolleringAuthorization__UseProtocollering=false
      - Ecs__Path=/var/log/historie-data-service.json
      - Ecs__FileSizeLimitBytes=1073741824
      - Ecs__RetainedFileCountLimit=10
      - Serilog__MinimumLevel__Default=Warning
      - Serilog__MinimumLevel__Override__Serilog=Information
    ports:
      - "8000:80"
    volumes:
      - ../test-data/logs:/var/log
    networks:
      - brp-api-network

networks:
  brp-api-network:
   name: brp-api-network
