name: Get version in Docker manifest
description: Get the version of the container image in a docker manifest

inputs:
  path-docker-manifest:
    description: the path of a docker manifest
    required: true
outputs:
  version:
    description: the version of the container image in the docker manifest
    value: ${{ steps.get-version.outputs.APP_VERSION }}

runs:
  using: composite
  steps:
    - name: Get version
      id: get-version
      run: |
        echo "APP_VERSION=$(sed -n 's/.*image:.*:\(.*\)-.*/\1/p' ${{ inputs.path-docker-manifest }})" >> $GITHUB_OUTPUT
      shell: bash
