version: '3.4'

services:
  api:
    image: ghcr.io/iswish-software/api:latest
    build:
      context: .
      dockerfile: api/Dockerfile
      platforms:
        - linux/arm64
        - linux/amd64
