name: continuous integration

on:
  push:
  workflow_dispatch:

env:
  APP_CSPROJ: src/api/api.csproj

jobs:
  set-workflow-vars:
    runs-on: ubuntu-latest
    outputs:
      BUILD_RUN: ${{ steps.get-build-run-identifier.outputs.build-run }}
      APP_CSPROJ: ${{ env.APP_CSPROJ }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Get build run identifier
        id: get-build-run-identifier
        uses: ./.github/actions/get-build-run-identifier
      - run: echo ${{ steps.get-build-run-identifier.outputs.build-run }}
  publish:
    needs: set-workflow-vars
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set build run in version in csproj
        id: set-app-version
        uses: ./.github/actions/set-version-build-run-in-csproj
        with:
          path-csproj-file: ${{ needs.set-workflow-vars.outputs.APP_CSPROJ }}
          build-run: ${{ needs.set-workflow-vars.outputs.BUILD_RUN }}
      - run: echo '"${{ steps.set-app-version.outputs.version }}"'
      - run: cat ${{ needs.set-workflow-vars.outputs.APP_CSPROJ }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          driver: docker-container
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: src/api/Dockerfile
          context: src
          push: true
          tags: ghcr.io/iswish-software/api-multiplatform-latest
          platforms: linux/arm64,linux/amd64
      # - run: docker compose -f src/docker-compose.yml build
      # - run: docker compose -f src/docker-compose.yml push
      # - run: docker compose -f src/docker-compose.yml up -d
      # - run: sleep 5s
      #   shell: bash
      # - run: docker compose -f src/docker-compose.yml down
      # - run: docker image push ghcr.io/iswish-software/api-amd64:latest
      # - run: docker image push ghcr.io/iswish-software/api-arm64:latest
      # - run: docker image push ghcr.io/iswish-software/api-multi-platform:latest
