on:
  workflow_dispatch:

jobs:
  run-bash-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: ./.github/actions/set-run-bash-scripts-permission
        with:
          path-bash-file-or-folder: ./scripts/*
      - run: ./scripts/foo.sh
